### ISSUE TITLE
突然不能连接了

### ISSUE THREAD

**Issue by jdfq** [XndroidDev/Xndroid#52]
刚启动时后，会出现连接正常的显示，马上就未连接了。此时teredo显示正常，IP在增长。重启、重置程序都不行

**Comment by jdfq** [comment]
好像是因为我的appid流量耗尽

**Comment by jdfq** [comment]
但是刚才还正常的火狐上的YouTube网页就显示安全连接失败了。点击下载证书，只是刷新了网页，没有其他反应

**Comment by jdfq** [comment]
谷歌还是正常的

**Comment by jdfq** [comment]
An error occurred during a connection to m.youtube.com. Peer’s certificate has an invalid signature. Error code: SEC_ERROR_BAD_SIGNATURE

**Comment by XndroidDev** [comment]
Xndroid版本?
1.1.7可以试试点击`更换服务器` (服务器地址域名留空就行)

**Comment by jdfq** [comment]
就是此版。就是留空。除了谷歌，包括推特，火狐都提示上面的错误

**Comment by jdfq** [comment]
谷歌是因为是http。怎么证书不对了？不懂怎么改火狐证书，就清除火狐数据，重新安装证书，正常了

**Comment by ruey-cn** [comment]
我也这两天一直在看刚启动后，过一会儿就不能连接的情况。我发现一直出现这样的请求

`> [192.168.137.156:48385 => 172.217.24.10:443 chromesyncpasswords-pa.googleapis.com HttpConnectProxy[127.0.0.1:8087 0.01]] http connect 127.0.0.1:8087`

因为现在fqrouter是每一个请求都要新开一个socket，由于打开的socket过多，fqrouter的pyth进程打开文件数超过了1024，结果就不能再响应请求了，报
```
2018-01-29 17:15:11,401 DEBUG [192.168.137.156:43484 => 172.217.160.74:443 chromesyncpasswords-pa.googleapis.com HttpConnectProxy[127.0.0.1:8087 0.01]] upstream connected
Traceback (most recent call last):
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/baseserver.py", line 140, in _do_read
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/server.py", line 93, in do_read
  File "/home/dejavu/Projects/python-for-android/build/python-install/lib/python2.7/site-packages/gevent/socket.py", line 307, in accept
error: [Errno 24] Too many open files
<StreamServer at 0xf6300a90L fileno=26 address=10.1.2.3:12345 handle=handle> failed with error
```
我使用了ulimit -n 2048来设置，发现在android系统上不起作用。也不知道android上如何修改这个限制。
希望有人能指教

**Comment by XndroidDev** [comment]
@ruey-cn 
没道理会有有这么多fd, 我开了两天也才几十个fd, 应该不存在fd泄漏. 你是运行多久后出现这样的情况?
`一直出现这样的请求`是怎么回事? 浏览器有问题吗, 莫非浏览器短时间打开大量socket而不关闭, 类似于dos?
至于`ulimit -n 2048`, 可能是因为ulimit 是shell内建命令(就像cd命令一样), 只对当前会话下新启动的进程有效. 运行XX-Net和fqrouter时会执行`su`命令(或`sh`命令), 在另一个会话中运行.
你可以试试将这个命令添加到`/data/data/net.xndroid/files/xndroid_files/python/bin/python-with-pie`开头

**Comment by tradeshark** [comment]
好像是启动的时候google服务就会发起很多syncpasssword的请求,很多端口都处在established的状态。我删掉google账户就没有这个请求了。我试试在启动脚本中增加ulimit试试看。

2018年2月1日 上午11:29，"XndroidDev" <notifications@github.com>写道：

@ruey-cn <https://github.com/ruey-cn>
没道理会有有这么多fd, 我开了两天也才几十个fd, 应该不存在fd泄漏. 你是运行多久后出现这样的情况?
一直出现这样的请求是怎么回事? 浏览器有问题吗, 莫非浏览器短时间打开大量socket而不关闭, 类似于dos?
至于ulimit -n 2048, 可能是因为ulimit 是shell内建命令(就像cd命令一样), 只对当前会话下新启动的进程有效.
运行XX-Net和fqrouter时会执行su命令(或sh命令), 在另一个会话中运行.
你可以试试将这个命令添加到/data/data/net.xndroid/files/xndroid_files/
python/bin/python-with-pie开头

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/XndroidDev/Xndroid/issues/52#issuecomment-362147616>,
or mute the thread

**Comment by tradeshark** [comment]
增加到python-launcher.sh脚本中起作用的。 打印出 /proc/进程号/limits确实改为2048了。再观察看看够用不。

2018年2月2日 上午9:05，"R He" <herui1983@gmail.com>写道：

**Comment by ruey-cn** [comment]
好像是系统启动的时候google服务就会发起很多syncpasssword的请求,很多端口都处在established的状态。我删掉google账户就没有这个请求了。
增加到python-launcher.sh脚本中起作用的。 打印出 /proc/进程号/limits确实改为2048了。
再观察看看够用不。@XndroidDev
